steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/eso-cloud-infra-01/github_dkuefner_hello-world-go/master:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/eso-cloud-infra-01/github_dkuefner_hello-world-go/master:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'hello-world-app'
  - '--image'
  - 'gcr.io/eso-cloud-infra-01/github_dkuefner_hello-world-go/master:$SHORT_SHA'
  - '--region'
  - 'europe-west3'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- gcr.io/eso-cloud-infra-01/github_dkuefner_hello-world-go/master:$SHORT_SHA